### ISSUE TITLE
how to fetch transaction history in specific pool ?

### ISSUE THREAD

**Issue by zach030** [fuzzyyeti/whirlpools-new-sdk-example#1]
Hi, I tried to run your example to fetch transaction history in specific pool such as "usdc-sol". 
Cause I am new to this project and not familiar with the SDK, would you like to get an example for that? 
Thanks a lot

**Comment by fuzzyyeti** [comment]
Sure. I can add an example for that. Just to make sure you are aware, the most comprehensive documentation for using the SDK is on the [Orca Developer Portal](https://orca-so.gitbook.io/orca-developer-portal/orca/welcome). Also, you can get support on Orca's Discord server.

**Comment by zach030** [comment]
> 

Thanks, I will checkout official documentation
